ALTER TABLE "QueuedJob"
  ADD COLUMN IF NOT EXISTS "attempts" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "lastError" TEXT,
  ADD COLUMN IF NOT EXISTS "bullJobId" TEXT;

ALTER TABLE "PullRequestReview"
  ADD COLUMN IF NOT EXISTS "outcome" TEXT,
  ADD COLUMN IF NOT EXISTS "checkRunId" TEXT;

ALTER TABLE "ReviewFinding"
  ADD COLUMN IF NOT EXISTS "fingerprint" TEXT;

CREATE INDEX IF NOT EXISTS "ReviewFinding_fingerprint_idx"
  ON "ReviewFinding"("fingerprint");
